# Generated by Django 2.2.26 on 2022-02-26 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20220226_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=256)),
                ('datedebut', models.DateTimeField()),
                ('datefin', models.DateTimeField()),
                ('lieu', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('categorie', models.CharField(blank=True, max_length=256, null=True)),
                ('idevenement', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='categories',
        ),
        migrations.AddField(
            model_name='listecategorie',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='listecategorie_articles', to='home.Articles'),
        ),
        migrations.AddField(
            model_name='listecategorie',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='listecategorie_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
